require("genre")
require("themes")
require("manufacturers")
require("consoles")
require("reveiws")
require("extrabooks")
require("consolesprites")
require("consoleparts")
require("events")
require("Letsplays")
--require("advers") --Buggy as f

--Released Interviwers
spritesheetParser:parse("letsplays/VeteranXT")
spritesheetParser:parse("letsplays/PewDiePie")
spritesheetParser:parse("letsplays/Markize")
--Released Interviwers
spritesheetParser:parse("Interviewrs/radar")
spritesheetParser:parse("Interviewrs/rockpaper")

--Released Consoles
spritesheetParser:parse("ConsoleReleased/A0")
spritesheetParser:parse("ConsoleReleased/A1")
spritesheetParser:parse("ConsoleReleased/A2")
spritesheetParser:parse("ConsoleReleased/A3")
spritesheetParser:parse("ConsoleReleased/A4")
spritesheetParser:parse("ConsoleReleased/A5")
spritesheetParser:parse("ConsoleReleased/A6")
spritesheetParser:parse("ConsoleReleased/C00")
spritesheetParser:parse("ConsoleReleased/C1")
spritesheetParser:parse("ConsoleReleased/C2")
spritesheetParser:parse("ConsoleReleased/C3")
spritesheetParser:parse("ConsoleReleased/C4")
spritesheetParser:parse("ConsoleReleased/C5")

--Player develop Console Cases
spritesheetParser:parse("ConsoleCases/a1")
spritesheetParser:parse("ConsoleCases/a2")
spritesheetParser:parse("ConsoleCases/a3")
spritesheetParser:parse("ConsoleCases/a4")
spritesheetParser:parse("ConsoleCases/a5")
spritesheetParser:parse("ConsoleCases/a6")
spritesheetParser:parse("ConsoleCases/a7")
spritesheetParser:parse("ConsoleCases/a8")
spritesheetParser:parse("ConsoleCases/a9")
spritesheetParser:parse("ConsoleCases/a10")
spritesheetParser:parse("ConsoleCases/a11")
spritesheetParser:parse("ConsoleCases/a12")
spritesheetParser:parse("ConsoleCases/a13")
spritesheetParser:parse("ConsoleCases/a14")
spritesheetParser:parse("ConsoleCases/a15")
spritesheetParser:parse("ConsoleCases/a16")
spritesheetParser:parse("ConsoleCases/a17")
spritesheetParser:parse("ConsoleCases/a19")
spritesheetParser:parse("ConsoleCases/a20")
spritesheetParser:parse("ConsoleCases/a21")
spritesheetParser:parse("ConsoleCases/a22")
spritesheetParser:parse("ConsoleCases/a23")
spritesheetParser:parse("ConsoleCases/a24")
spritesheetParser:parse("ConsoleCases/a25")
spritesheetParser:parse("ConsoleCases/a26")
spritesheetParser:parse("ConsoleCases/a27")
spritesheetParser:parse("ConsoleCases/a28")
spritesheetParser:parse("ConsoleCases/a29")
spritesheetParser:parse("ConsoleCases/a30")
spritesheetParser:parse("ConsoleCases/a31")
spritesheetParser:parse("ConsoleCases/a33")
spritesheetParser:parse("ConsoleCases/a34")
spritesheetParser:parse("ConsoleCases/a35")
spritesheetParser:parse("ConsoleCases/a36")
spritesheetParser:parse("ConsoleCases/a37")
spritesheetParser:parse("ConsoleCases/a38")
spritesheetParser:parse("ConsoleCases/a39")
spritesheetParser:parse("ConsoleCases/a40")
spritesheetParser:parse("ConsoleCases/a41")
spritesheetParser:parse("ConsoleCases/a42")
spritesheetParser:parse("ConsoleCases/a43")
spritesheetParser:parse("ConsoleCases/a44")
spritesheetParser:parse("ConsoleCases/a45")
spritesheetParser:parse("ConsoleCases/a46")
spritesheetParser:parse("ConsoleCases/a47")

--Console Extra parts
spritesheetParser:parse("ConsoleParts/Cpu_1")
spritesheetParser:parse("ConsoleParts/Cpu_2")



print("ExtraStuff was loaded successfully!")